### ISSUE TITLE
ValueError: list.remove(x): x not in list

### ISSUE THREAD

**Issue by BenjaminRamila** [frescobaldi/frescobaldi#1770] opened 2024-07-02 02:35 UTC
Traceback (most recent call last):
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.10/frescobaldi_app/historymanager.py", line 68, in setCurrentDocument
ValueError: list.remove(x): x not in list

Optionally describe below what you were doing:

Frescobaldi: 3.3.0
Extension API: 0.9.0
Python: 3.10.10
python-ly: 0.9.7
Qt: 5.15.3
PyQt: 5.15.7
sip: 6.6.2
qpageview: 0.6.2
poppler: 22.9.0
python-poppler-qt: 21.3.0
OS: macOS-14.1.1-x86_64-i386-64bit
installation kind: standalone .app bundle

**Comment by fedelibre** [comment] 2024-07-02 08:02
Duplicate of #1324 (which contains a description of what triggers the error)

@jeanas Don't you think that the description of what the user was doing should not be optional? We receive many bug reports without any hint on what might have triggered the bug.

**Closed by fedelibre** 2024-07-02 08:02 UTC
