### ISSUE TITLE
Internal error on MacOS after installing Frescobaldi 3.1.3

### ISSUE THREAD

**Issue by ratnay** [frescobaldi/frescobaldi#1430] opened 2022-04-10 04:54 UTC
I recently installed Friscobaldy on my MAC OS `version10.14.6`

My lilypond is up to date still i'm getting this issue 
saying "An internal error has occurred", i got this error after i resolved issue #1386
Frescobaldi: 3.1.3
Extension API: 0.9.0
Python: 3.9.1
python-ly: 0.9.7
Qt: 5.11.3
PyQt: 5.15.2
sip: 4.19.24
poppler: 20.12.1
python-poppler-qt: 0.75.0
OS: macOS-10.14.6-x86_64-i386-64bit
installation kind: standalone .app bundle

Traceback (most recent call last):
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.9/frescobaldi_app/engrave/__init__.py", line 145, in engravePreview
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.9/frescobaldi_app/engrave/__init__.py", line 200, in engrave
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.9/frescobaldi_app/engrave/__init__.py", line 252, in runJob
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.9/frescobaldi_app/job/manager.py", line 61, in start_job
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.9/frescobaldi_app/job/__init__.py", line 225, in start
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.9/frescobaldi_app/job/__init__.py", line 304, in _update_process_environment
TypeError: arguments did not match any overloaded call:
  insert(self, str, str): argument 2 has unexpected type 'bool'
  insert(self, QProcessEnvironment): argument 1 has unexpected type 'str'

**Comment by dliessi** [comment] 2022-04-10 17:11
Duplicate of #1419.

**Closed by dliessi** 2022-04-10 17:11 UTC
