### ISSUE TITLE
Weird issues with UI scaling on high screen resolution

### ISSUE THREAD

**Issue by semininja** [frescobaldi/frescobaldi#1754] opened 2024-03-31 21:20 UTC
![image](https://github.com/frescobaldi/frescobaldi/assets/15026607/6124f8e8-534c-4202-b82f-3a30f411fe77)

I'm encountering very strange UI/text scaling inconsistency with version 3.3.0 on Windows 10. Version 3.2 looks normal on the same system.

Please let me know what info I can provide to help diagnose this issue.

**Comment by bmjcode** [comment] 2024-11-21 13:23
This looks like a Qt bug. I reproduced the behavior on mine (also running 3.3.0 under Windows 10) by dragging a window from my high-DPI laptop screen to a lower-resolution external monitor.

The Qt 6 version in development now does not have this problem, so it should be fixed in our next release.

**Closed by bmjcode** 2024-11-21 13:23 UTC
