### ISSUE TITLE
wish: tweak tool

### ISSUE THREAD

**Issue by Nick-Payne** [frescobaldi/frescobaldi#107] opened 2013-03-16 22:47 UTC
Something similar to LilyPondTool's tweak tool, where you can drag an element to it's desired location in the PDF preview and the values to apply to the tweak command, already setup in the correct format, are generated for you and copied to the clipboard.

**Comment by uliska** [comment] 2019-08-30 08:47
While completely valid as a feature request I think it is by now a duplicate of (at least) #284

**Closed by uliska** 2019-08-30 08:47 UTC
Labels: wish
