### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'document'

### ISSUE THREAD

**Issue by michaelmariaott** [frescobaldi/frescobaldi#1744] opened 2024-03-13 11:22 UTC
Traceback (most recent call last):
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.10/frescobaldi_app/engrave/autocompile.py", line 113, in slotTimeout
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.10/frescobaldi_app/engrave/__init__.py", line 258, in runJob
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.10/frescobaldi_app/job/manager.py", line 62, in start_job
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.10/frescobaldi_app/signals.py", line 191, in emit
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.10/frescobaldi_app/signals.py", line 308, in call
AttributeError: 'NoneType' object has no attribute 'document'

Optionally describe below what you were doing:

Frescobaldi: 3.3.0
Extension API: 0.9.0
Python: 3.10.10
python-ly: 0.9.7
Qt: 5.15.8
PyQt: 5.15.9
sip: 6.7.6
qpageview: 0.6.2
poppler: 23.3.0
python-poppler-qt: 21.3.0
OS: macOS-14.2.1-arm64-arm-64bit
installation kind: standalone .app bundle

**Comment by jeanas** [comment] 2024-03-13 11:28
Duplicate of #1645

**Closed by jeanas** 2024-03-13 11:28 UTC
