### ISSUE TITLE
ValueError: list.remove(x): x not in list

### ISSUE THREAD

**Issue by ctptincomp** [frescobaldi/frescobaldi#1773] opened 2024-07-22 20:04 UTC
Traceback (most recent call last):
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.10/frescobaldi_app/historymanager.py", line 68, in setCurrentDocument
ValueError: list.remove(x): x not in list

Optionally describe below what you were doing: trying to open a file in Frescobaldi/Lilypond

Frescobaldi: 3.3.0
Extension API: 0.9.0
Python: 3.10.10
python-ly: 0.9.7
Qt: 5.15.8
PyQt: 5.15.9
sip: 6.7.6
qpageview: 0.6.2
poppler: 23.3.0
python-poppler-qt: 21.3.0
OS: macOS-14.3.1-arm64-arm-64bit
installation kind: standalone .app bundle

**Comment by fedelibre** [comment] 2024-07-23 06:01
Duplicate of #1324 

Please search the error in the issue tracker before opening a new issue.

**Closed** 2024-07-23 06:01 UTC
