### ISSUE TITLE
Launch fails on Windows 10

### ISSUE THREAD

**Issue by BruceP99166** [frescobaldi/frescobaldi#1363] opened 2021-03-23 20:45 UTC
Greetings.  I installed Frescobaldi 3.1.3.  At the end of the install, clicked ok to start frescobaldi; worked ok.  However, when I attempt to start Frescobaldi from the Start menu, I get the error shown in the attached screenshot.
![Frescobaldi error](https://user-images.githubusercontent.com/17090922/112215726-52a1b380-8be6-11eb-9a34-2a95fd3a5e1e.png)

Thanks in advance for your assistance.

**Comment by fedelibre** [comment] 2021-03-24 14:29
Yet another duplicate of #1252 

Uninstall and then install again.

**Closed by fedelibre** 2021-03-24 14:29 UTC

**Comment by BruceP99166** [comment] 2021-03-25 01:13
Thanks for your assistance.  In addition to uninstalling, it's also necessary to unpin from Start in order to get rid of the old start icon.
