### ISSUE TITLE
3.1.3 opens to a nonfunctional state on Mac OS 11.6 (Big Sur)

### ISSUE THREAD

**Issue by marnen** [frescobaldi/frescobaldi#1403] opened 2021-11-11 21:57 UTC
I just downloaded the 3.1.3 DMG and tried to run it on Big Sur. It shows the splash screen and menus, but then basically nothing works after that.

* If I choose File | New | Score Wizard…, the wizard does not appear and all the menus (except the Application menu) vanish, so I can't do anything except quit the application.
* If I switch to another application and then switch back to Frescobaldi, the menus are gone (except the Application menu, as above).
* Window | New Window has no apparent effect

If I double-click on the Frescobaldi icon in the Finder _after_ the application is already open, then a document window opens and I can use the application normally, but I shouldn't have to open the application twice for that to happen. :) Any suggestions? Can I provide better bug report information?

**Comment by fedelibre** [comment] 2023-01-24 22:32
3.1.3 was the latest release providing a .dmg, which is missing in 3.2.

Don't  know what will happen with next release, but let's close this issue, since it's about an old release.

**Comment by marnen** [comment] 2023-01-25 03:46
@fedelibre I’m not sure why we’d close this, particularly if the buggy release is still the latest one for which a DMG is available.

**Comment by dliessi** [comment] 2023-03-25 00:23
This has been the case for the standalone app bundle for a long time, see #428. I wasn't able at that time to determine whether it is a bug in Frescobaldi or in (Py)Qt. For some users disabling the splashscreen helped, but not always. Usually (or, in my experience, always) a single click on Frescobaldi's icon after the splashscreen disappears is enough to make the window appear and everything work as expected.

**Comment by dliessi** [comment] 2023-03-25 00:24
I'm closing this as a duplicate of #428. If there is something I overlooked feel free to reopen it.

**Closed by dliessi** 2023-03-25 00:24 UTC
Labels: macOS
