### ISSUE TITLE
Exception when selecting a `\breathe`

### ISSUE THREAD

**Issue by qtlis** [frescobaldi/frescobaldi#1417] opened 2022-01-24 11:53 UTC
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/frescobaldi_app/musicview/widget.py", line 212, in slotCursorPositionChanged
    self.showCurrentLinks(
  File "/usr/lib/python3.10/site-packages/frescobaldi_app/musicview/widget.py", line 264, in showCurrentLinks
    self.view.highlight(areas, self._highlightMusicFormat, msec)
  File "/usr/lib/python3.10/site-packages/qpageview/highlight.py", line 146, in highlight
    t.start(msec)
TypeError: arguments did not match any overloaded call:
  start(self, int): argument 1 has unexpected type 'float'
  start(self): too many arguments
```

#### How to reproduce:

In a new file, enter `{ a \breathe }`, then play around by selecting it, deselecting it, selecting it in the music preview…

Similar exceptions show up in other situations, all related to selections, but this is the first I could reliably reproduce.

#### System specs:
Artix Linux, Python 3.10, Lilypond 2.23.5, Frescobaldi and qpageview at latest commits at the time of writing

**Comment by qtlis** [comment] 2022-01-24 12:55
This bug seems very flaky, I cannot reproduce it like above currently, but it still shows up often when selecting things in more complex files.

![Screenshot_20220124_134449](https://user-images.githubusercontent.com/15247429/150786021-68b703eb-7cb6-40e2-a545-73f161e94a0e.png)

For some reason `msec` just is a float sometimes. Probably doesn't hurt to just cast it at some point.

**Comment by fedelibre** [comment] 2022-01-27 14:01
I can reproduce it easily using the Ctrl+J shortcut (aka reverse point-and-click).
Here's the traceback:

```
Traceback (most recent call last):
  File "/var/home/fede/src/frescobaldi/frescobaldi/frescobaldi_app/musicview/__init__.py", line 79, in wrapper
    func(self)
  File "/var/home/fede/src/frescobaldi/frescobaldi/frescobaldi_app/musicview/__init__.py", line 180, in jumpToCursor
    self.widget().showCurrentLinks(True, 10000)
  File "/var/home/fede/src/frescobaldi/frescobaldi/frescobaldi_app/musicview/widget.py", line 264, in showCurrentLinks
    self.view.highlight(areas, self._highlightMusicFormat, msec)
  File "/var/home/fede/.local/lib/python3.10/site-packages/qpageview/highlight.py", line 146, in highlight
    t.start(msec)
TypeError: arguments did not match any overloaded call:
  start(self, int): argument 1 has unexpected type 'float'
  start(self): too many arguments
```

This happens using Frescobaldi current master and qpageview installed from the PyPI.

**Comment by fedelibre** [comment] 2023-02-27 15:29
I confirm I cannot reproduce it anymore when I use the Ctrl+J shortcut.

```
$ rpm -q python3-qpageview
python3-qpageview-0.6.2-2.fc37.noarch
```

Let's close it.

**Closed by fedelibre** 2023-02-27 15:29 UTC
