### ISSUE TITLE
RuntimeError: wrapped C/C   object of type TabBar has been deleted

### ISSUE THREAD

**Issue by mbolognani** [frescobaldi/frescobaldi#1719] opened 2023-12-20 18:35 UTC
Traceback (most recent call last):
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.10/frescobaldi_app/macosx/file_open_eventhandler.py", line 58, in eventFilter
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.10/frescobaldi_app/macosx/file_open_eventhandler.py", line 50, in openUrl
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.10/frescobaldi_app/mainwindow.py", line 433, in openUrl
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.10/frescobaldi_app/mainwindow.py", line 457, in openUrls
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.10/frescobaldi_app/app.py", line 106, in openUrl
RuntimeError: wrapped C/C   object of type TabBar has been deleted

È possibile descrivere sotto quel che si stava facendo:

Frescobaldi: 3.3.0
Extension API: 0.9.0
Python: 3.10.10
python-ly: 0.9.7
Qt: 5.15.8
PyQt: 5.15.9
sip: 6.7.6
qpageview: 0.6.2
poppler: 23.3.0
python-poppler-qt: 21.3.0
OS: macOS-14.1.2-arm64-arm-64bit
installation kind: standalone .app bundle

**Comment by jeanas** [comment] 2023-12-20 18:36
Duplicate of https://github.com/frescobaldi/frescobaldi/issues/1467

**Closed by jeanas** 2023-12-20 18:36 UTC
