### ISSUE TITLE
Flatpak version crashes within a few minutes (Wayland/X11)

### ISSUE THREAD

**Issue by RyuKurisu** [frescobaldi/frescobaldi#1373] opened 2021-05-24 05:34 UTC
Hi everyone,

Thanks a lot for providing a Flatpak, as that **should** be the main mode for installing apps in Fedora Kinoite/Silverblue.  I've noticed it picks up the dark mode nicely.

However it crashes without user interaction within a few minutes on both Wayland **and X11**.  When starting Frescobaldi from the terminal I only get a warning message in the Wayland session (which I'll upload when I'm on my laptop, hopefully later today).

I read in an other post that I can get a core dump with coredumpctl PID-of-Frescobaldi?  I'll see if I can also get that.

Luckily for me I could install Frescobaldi in a `toolbox` 😎👍

**Comment by fedelibre** [comment] 2021-05-26 15:26
Hi, I'm the maintainer of the flatpak.

I've just installed Fedora 34 Silverblue on my desktop computer. I installed also Frescobaldi flatpak (from stable repository) and I cannot reproduce any crash.

I see some Qt errors in the terminal, but nothing important (hopefully):

```
$ flatpak run org.frescobaldi.Frescobaldi
Failed to create wl_display (No such file or directory)
qt.qpa.plugin: Could not load the Qt platform plugin "wayland" in "" even though it was found.
Gtk-Message: 17:15:36.642: Failed to load module "canberra-gtk-module"
Gtk-Message: 17:15:36.642: Failed to load module "canberra-gtk-module"
Qt: Session management error: None of the authentication protocols specified are supported
qt.qpa.xcb: QXcbConnection: XCB error: 11 (BadAlloc), sequence: 435, resource id: 8388614, major code: 147 (Unknown), minor code: 7
qt.qpa.xcb: QXcbConnection: XCB error: 9 (BadDrawable), sequence: 436, resource id: 8388617, major code: 147 (Unknown), minor code: 4
```

**Comment by fedelibre** [comment] 2021-05-26 15:30
Which dark theme are you using in your system? And how did you set it up? (did you install gnome-tweaks via rpm-ostree?)

**Comment by RyuKurisu** [comment] 2021-05-26 20:53
Hi @fedelibre,

I have converted Silverblue to Kinoite (which is the KDE version of the rpm-ostree builds).  I've used this guide to do so: https://fedoramagazine.org/discover-fedora-kinoite/ (be sure to update all flatpaks before converting)

When I run that command I only get this:

```
[ryukurisu@fedora ~]$ time flatpak run org.frescobaldi.Frescobaldi 
Failed to create wl_display (No such file or directory)
qt.qpa.plugin: Could not load the Qt platform plugin "wayland" in "" even though it was found.

real    0m33,368s
user    0m0,076s
sys     0m0,086s
```
I added `time` to acquire the time after which it crashes, which is apparently about 30 seconds on my "netbook" when just idling after starting it.

The dark theme I'm using it Breeze Dark, set up with Plasma's System Setting.

(I'll switch to X11 now to see if it shows anything noteworthy.  If so I'll post another comment.)

**Comment by RyuKurisu** [comment] 2021-05-26 20:59
Hi @fedelibre,

I have converted Silverblue to Kinoite (which is the KDE version of the rpm-ostree builds).  I've used this guide to do so: https://fedoramagazine.org/discover-fedora-kinoite/ (be sure to update all flatpaks before converting)

When I run that command I only get this:

```
[ryukurisu@fedora ~]$ time flatpak run org.frescobaldi.Frescobaldi 
Failed to create wl_display (No such file or directory)
qt.qpa.plugin: Could not load the Qt platform plugin "wayland" in "" even though it was found.

real    0m33,368s
user    0m0,076s
sys     0m0,086s
```
I added `time` to acquire the time after which it crashes, which is apparently about 30 seconds on my "netbook" when just idling after starting it.

The dark theme I'm using it Breeze Dark, set up with Plasma's System Setting.

(I'll switch to X11 now to see if it shows anything noteworthy.  If so I'll post another comment.)

UPDATE:
No errors but still crashing after about a minute:
```
[ryukurisu@fedora ~]$ time flatpak run org.frescobaldi.Frescobaldi 

real    0m52,524s
user    0m0,089s
sys     0m0,131s
```

**Comment by RyuKurisu** [comment] 2021-05-26 21:41
Switching to X11 broke the system again (removing all rpm-ostree apps besides the flatpaks) I had the boot an snapshot.  This time I agreed to `running in background` and now it doesn't break within a minute.

I guess I've found the problem, but I don't understand why it should be "run in the background" (the notification also mentions that "it should be run in the background, but that wasn't properly defined why it should")

**Comment by fedelibre** [comment] 2021-05-26 22:09
I played with the *Run in background* option (in GNOME settings) and it doesn't cause any problem on my system.

I suspect there's something wrong either with the theme or with Kinoite. I'll try to reproduce the crash.

**Comment by fedelibre** [comment] 2021-05-26 22:18
What's the output of this command?

```
grep guistyle ~/.var/app/org.frescobaldi.Frescobaldi/config/frescobaldi/frescobaldi.conf
```

It may be empty if you're using the default style/theme.

**Comment by RyuKurisu** [comment] 2021-05-27 04:20
Yep, completely empty :(

**Comment by fedelibre** [comment] 2021-05-27 08:13
Please paste the output of `rpm-ostree status`.

**Comment by RyuKurisu** [comment] 2021-05-27 20:39
Here it is:
```
[ryukurisu@fedora ~]$ rpm-ostree status
State: idle
Deployments:
● ostree://kinoite:fedora/34/x86_64/kinoite
                   Version: Kinoite 34.20210517.0 (2021-05-17T12:30:04Z)
                    Commit: 5fd0c525b4959b5088aff1fefa33d0b1432da2a168621511f72f98c69fbefde6
              GPGSignature: Valid signature by C8D83B6AE4B8685A7290545FDB27818F78688F83

  ostree://fedora:fedora/34/x86_64/silverblue
                   Version: 34.20210520.0 (2021-05-20T00:44:26Z)
                    Commit: a2feef03926f00b8897444990e03f57c056a6c932c1a91efa59974b275a5c995
              GPGSignature: Valid signature by 8C5BA6990BDB26E19F2A1A801161AE6945719A39
                    Pinned: yes
```

**Comment by RyuKurisu** [comment] 2021-05-29 19:23
@fedelibre do you want me to close this bug for now?

**Comment by fedelibre** [comment] 2021-05-30 22:47
Yes, let's close it.

I've set up Kinoite in a virtual machine, changed the theme to Dark Breeze, installed and tested Frescobaldi. No crash at all.

At first run I was asked to give Frescobaldi the permission to run it in background. I answered yes and then I saw a message saying that xdg-desktop-portal-kde crashed.

**Closed by fedelibre** 2021-05-30 22:47 UTC
