### ISSUE TITLE
after installation, Frescobaldi does not loadproperly , Windows

### ISSUE THREAD

**Issue by gfischeraut** [frescobaldi/frescobaldi#1354] opened 2021-01-19 15:02 UTC
![image](https://user-images.githubusercontent.com/31270809/105051391-fe0b7c00-5a6e-11eb-962d-339c3326ab77.png)

I installed Frescobaldi (frescobaldi.setup.3.1.3) on a windows computer. the app did not load completely, but there was an errormessage ("cx_freeze"),  screenshot attached

Thank you
Gottfried

**Comment by fedelibre** [comment] 2021-01-19 15:57
Duplicate of #1252 

Current workaround: uninstall and reinstall from scratch.

**Closed by fedelibre** 2021-01-19 15:57 UTC
