### ISSUE TITLE
Music viewer does not display properly on wide monitor

### ISSUE THREAD

**Issue by hrtsgs** [frescobaldi/frescobaldi#1781] opened 2024-08-17 14:08 UTC
![Screenshot from 2024-08-17 15-59-56](https://github.com/user-attachments/assets/8e048f4a-c149-4b21-a373-296300d26f56)
![Screenshot from 2024-08-17 16-01-56](https://github.com/user-attachments/assets/3c1babf8-1f33-4aa1-bde0-b0d2431d3d91)

Monitor resolution is 5120x1440.
Whether the music score should adjusted to width or height, viewer does not display properly.
But the music score is displayed normally on monitors with an aspect ratio of 16:9 or 16:10.

**Comment by jeanas** [comment] 2024-08-17 15:49
Thanks, but this is a duplicate of #1485.

**Closed** 2024-08-17 15:49 UTC

**Comment by hrtsgs** [comment] 2024-08-18 11:47
Ups sorry, my research was inadequate...
