### ISSUE TITLE
Qt font warning

### ISSUE THREAD

**Issue by Davidrobla** [frescobaldi/frescobaldi#1304] opened 2020-05-18 19:15 UTC
frescobaldi
qt.qpa.fonts: Populating font family aliases took 1695 ms. Replace uses of missing font family "Monospace" with one that exists to avoid this cost.

**Comment by dliessi** [comment] 2020-05-19 08:03
In https://github.com/frescobaldi/frescobaldi/issues/1244#issuecomment-629842494 you specify that you are running macOS 10.14 Mojave.

I too get the warning about the Monospace font, but that is harmless and does not prevent Frescobaldi from running (no need to install new fonts).
The cause for your problem must be something else.

Can you please run
```
/Applications/Frescobaldi.app/Contents/MacOS/Frescobaldi
```
in the Terminal and copy here any messages you get?
(Adapt the path if needed; you can use the tab key after writing a few letters for autocompletion in the Terminal.)

**Comment by Davidrobla** [comment] 2020-05-19 08:54
-bash: /Applications/Frescobaldi.app/Contents/MacOS/Frescobaldi: No such file or directory

This is the message in terminal

**Comment by fedelibre** [comment] 2020-05-19 11:28
As Davide wrote, don't use the exact command he wrote. Start typing `/Applications/Frescobaldi` and then press the TAB key to autocomplete the path and find your path, which is different from other people installations.

**Comment by Davidrobla** [comment] 2020-05-20 06:50
Output in my Terminal

MacBook-Air-de-David:~ davidrodriguezblanco$ /Applications/Frescobaldi.app/Contents/MacOS/Frescobaldi
-bash: /Applications/Frescobaldi.app/Contents/MacOS/Frescobaldi: No such file or directory

**Comment by dliessi** [comment] 2020-05-20 08:31
Apparently you have not installed Frescobaldi.app in the Applications directory.
As I wrote above, you must adapt the path to match what is in your system.
Let's do it another way.

1. Open a new Terminal window.
2. Drag and drop your Frescobaldi.app in the Terminal window: something ending with `.app` should appear.
3. Add `/Contents/MacOS/Frescobaldi` at the end of the line, with no spaces between `.app` and `/Contents...`.
4. Press enter: this should (try to) open Frescobaldi from the Terminal.
5. Copy here all the output.

**Comment by Davidrobla** [comment] 2020-05-20 15:42
He hecho lo que me mandaste y aparece esto, llevo así un mes y no hay manera de salir del entuerto. Tengo instalado Frescobaldi y lilpod
Gracias, pero si me ayudas a que pueda trabajar onFrescoabaldi y olivo estaré eternamente agradecido
Last login: Wed May 20 17:25:17 on ttys000
MacBook-Air-de-David:Frescobaldi.app davidrodriguezblanco$ 
MacBook-Air-de-David:Frescobaldi.app davidrodriguezblanco$ frescobaldi
qt.qpa.fonts: Populating font family aliases took 1782 ms. Replace uses of missing font family "Monospace" with one that exists to avoid this cost. 
/Users/davidrodriguezblanco/Downloads/LilyPond\ 2.app

**Comment by Davidrobla** [comment] 2020-05-20 15:48
Terminal abe sin problema Frescobaldi y Lilypod pero señala que Lilypod no está instalado, aunque lo tengo y que no encuentra el PATH o la ruta., pero en Python no me deja acceder a Preferencias y en el la app del desktop tapo porque aparece una cruz roja en la casilla preferencias lilypod

**Comment by Davidrobla** [comment] 2020-05-20 16:09
Last login: Wed May 20 17:43:11 on ttys000
MacBook-Air-de-David:~ davidrodriguezblanco$ frescobaldi
qt.qpa.fonts: Populating font family aliases took 1599 ms. Replace uses of missing font family "Monospace" with one that exists to avoid this cost.

**Comment by dliessi** [comment] 2020-05-21 00:16
I see that you are already running Frescobaldi from the Terminal: how did you install it? Manually or with MacPorts?

Judging from

> Last login: Wed May 20 17:25:17 on ttys000
> MacBook-Air-de-David:Frescobaldi.app davidrodriguezblanco$ frescobaldi
> qt.qpa.fonts: Populating font family aliases took 1782 ms. Replace uses of missing font family "Monospace" with one that exists to avoid this cost.
> /Users/davidrodriguezblanco/Downloads/LilyPond\ 2.app

I think you dragged LilyPond's application bundle on the Terminal instead of Frescobaldi's.
Anyway that's probably not important now.

Given the absence of errors in the Terminal output, I believe Frescobaldi i running correctly and you are simply seeing #428: does Frescobaldi's icon appear in the dock when you start it?
If you click on it, does Frescobaldi's window appear?

As for configuring Frescobaldi to find LilyPond, if it is not in a standard location you need to add your LilyPond installation in the preferences, pointing to the executable, e.g. `/opt/local/bin/frescobaldi` if you installed it with MacPorts, or to the application bundle (you can change the existing entry or add a new one).

When you run Frescobaldi from the command line, given that the main application menu is Python's and not Frescobaldi's, you can find the preferences in the "Edit" menu.

**Comment by Davidrobla** [comment] 2020-05-21 08:21
Last output in Terminal
Last login: Thu May 21 04:52:37 on console
MacBook-Air-de-David:~ davidrodriguezblanco$ /Users/davidrodriguezblanco/Downloads/LilyPond\ 3.app 
-bash: /Users/davidrodriguezblanco/Downloads/LilyPond 3.app: is a directory

**Comment by Davidrobla** [comment] 2020-05-21 08:21
Cda vez que abro el Terminal...
MacBook-Air-de-David:~ davidrodriguezblanco$ frescobaldi
qt.qpa.fonts: Populating font family aliases took 1581 ms. Replace uses of missing font family "Monospace" with one that exists to avoid this cost.

**Comment by Davidrobla** [comment] 2020-05-21 08:27
ast login: Thu May 21 04:52:37 on console
MacBook-Air-de-David:~ davidrodriguezblanco$ /Users/davidrodriguezblanco/Downloads/LilyPond\ 3.app 
-bash: /Users/davidrodriguezblanco/Downloads/LilyPond 3.app: is a directory
Cda vez que abro el Terminal...
MacBook-Air-de-David:~ davidrodriguezblanco$ frescobaldi
qt.qpa.fonts: Populating font family aliases took 1581 ms. Replace uses of missing font family "Monospace" with one that exists to avoid this cost.

**Comment by Davidrobla** [comment] 2020-05-21 20:38
Please say me what I can do, I not find solution because don’t know how executioner’s command and where

**Comment by Davidrobla** [comment] 2020-05-22 14:06
MacBook-Air-de-David:~ davidrodriguezblanco$ /opt/Local/bin/frescobaldi
qt.qpa.fonts: Populating font family aliases took 1681 ms. Replace uses of missing font family "Monospace" with one that exists to avoid this cost. 
Last output terminal, not runs

**Comment by dliessi** [comment] 2020-05-25 01:10
@Davidrobla I understand the language barrier is quite an issue here.
Unfortunately I cannot speak Spanish.
I tried translating this message into Italian with Google Translate and it did a rather good job, so that may help with the Spanish, too.

This is a long message.
I apologise for that, but I'm trying to be as complete as possible.
The questions I need you to answer and the tests I need you to perform will be in bold.

_First_, I want to reassure you that the warning from `qt.qpa.fonts` is harmless: it only informs you that looking for a replacement font took some time, but it does not prevent Frescobaldi from running.
I get the same warning on my machine and Frescobaldi runs as expected.

This means that technically I should close this issue because it is not a bug.
However, I understand that you are having some problems in using LilyPond and Frescobaldi.
I will keep the issue open and I will try to help you here.

_Second_, I suspect that your copy of Frescobaldi is running correctly and that you are simply experiencing the issue #428, which prevents Frescobaldi from showing its window when it is started (the cause of the problem is still unknown, but there are workarounds).

I am convinced of this because of the following elements:
* your latest message (where you run `/opt/local/bin/frescobaldi`) seems to confirm that you installed Frescobaldi with MacPorts, which very rarely gives rise to problems (when a new version of Frescobaldi is released, I package and test it with MacPorts first and only then I build the application bundle);
* the fact that when you run the program from the Terminal you only get the `qt.qpa.fonts` warning and no other warning or error message suggests that Frescobaldi has started, has not crashed and thinks everything is fine;
* in another message you mention that the "Python" menu lacks the "Preferences" entry and that you see a red cross in Frescobaldi's "LilyPond preferences", which suggests that Frescobaldi runs correctly, at least in some cases.

**Can you please confirm whether you installed Frescobaldi with MacPorts?**

**When you launch Frescobaldi from the Terminal does Frescobaldi's icon appear in the Dock (even if the main window is not shown) with the white dot next to it (which indicates that the application is running)?**

**If that is the case (i.e., if Frescobaldi's icon appears in the Dock), can you please click on it and check if Frescobaldi's main window appears?**

_Third_, judging from the file names in your messages, I suspect that you downloaded LilyPond's application bundle many times.
* If you want to keep only one version of LilyPond at a time, I advise you to put it in the directory `/Applications`, ensuring that its name is `LilyPond.app` (probably shown simply as `LilyPond`).
You can find the `/Applications` directory by opening the Finder and selecting "Applications" in the "Go" menu (or by pressing command+shift+A).
You can then move LilyPond's application from the "Downloads" directory, renaming it if needed.
* If you want to keep multiple versions of LilyPond at a time, I advise you to rename each application to contain the version number in the name (e.g., `LilyPond-2.20.0.app`) and move it into the `/Applications` directory as explained above.

Anyway, independently of where the copy of LilyPond's application bundle actually resides, in Frescobaldi's "LilyPond preferences" you can add as many different versions of LilyPond as you want.
**If at this point you have Frescobaldi running, open the "Preferences" (when run Frescobaldi from the Terminal, the "Preferences" menu entry is in the "Edit" menu) and click on "Add" in Frescobaldi's "LilyPond preferences".
In the text box "LilyPond command" you must insert the path to LilyPond's application bundle: the easiest way is to click on the directory button next to the text box, browse to the correct directory and select the application bundle.**

**Comment by Davidrobla** [comment] 2020-05-26 04:16
Thank you for your mail and for your time. I apologize for my English and my inhability.
I try to answer your questions in bold:
Frescobaldi was installed with GitHub but I also downland MacPorts, not sure if installation was completed with with GItHub or MacPorts.
In my Desktop I can see the Frescobaldi Icon and Lilypod icons, also booth are in Finder Applications.
Ihave remover all the lowlands fo Lilypod I ge Lilypon 6.24.49 app.
Frescobaldi inhalation says Congratulations   has been installed successfully and complete and compiled and a pop pdf sheet with music notes appears Conngratulations compitation completed successfully.
When I try to open Frescobaldi from Terminal or from the icon in Desktop the program runs without problems and open.In Terminal the Frescobaldi icon don’t appears in the Dock,when lunch inTerminal a por Python launcher icon pops in The Dock, when lunch for the Destop icono the Frescobaldi icon appears in the Dock.
Trying to set Preferences both with Terminal and from the Desktop the  program not l et me to accomplish it and always the same message:”Cannot init Lilypod, test the path and permissions adda in Preferences.
Sorry but the same problem continues.
I apologize, but I think I Cannot make it to run.
Thank y ou.

**Comment by Davidrobla** [comment] 2020-05-28 06:14
> El 26 may 2020, a las 6:15, David Rodríguez Blanco <ozadrb46@gmail.com> escribió:
> 
> Thank you for your mail and for your time. I apologize for my English and my inhability.
> I try to answer your questions in bold:
> Frescobaldi was installed with GitHub but I also downland MacPorts, not sure if installation was completed with with GItHub or MacPorts.
> In my Desktop I can see the Frescobaldi Icon and Lilypod icons, also booth are in Finder Applications.
> Ihave remover all the lowlands fo Lilypod I ge Lilypon 6.24.49 app.
> Frescobaldi inhalation says Congratulations   has been installed successfully and complete and compiled and a pop pdf sheet with music notes appears Conngratulations compitation completed successfully.
> When I try to open Frescobaldi from Terminal or from the icon in Desktop the program runs without problems and open.In Terminal the Frescobaldi icon don’t appears in the Dock,when lunch inTerminal a por Python launcher icon pops in The Dock, when lunch for the Destop icono the Frescobaldi icon appears in the Dock.
> Trying to set Preferences both with Terminal and from the Desktop the  program not l et me to accomplish it and always the same message:”Cannot init Lilypod, test the path and permissions adda in Preferences.
> Sorry but the same problem continues.
> I apologize, but I think I Cannot make it to run.
> Thank y ou.
> 
In Terminal I copied Lilypond app  6.24.49.app and says its is a directory , When I lunch Frescobaldi from Terminal it opens without problem but 
This message appears when I tr y to open it:
Frescobaldi usa LilyPond para procesar la música y producir la partitura, pero LilyPond no está instalado en las rutas predeterminadas y no se encuentra en su PATH.

Instale LilyPond o, si ya lo tiene instalado, añádalo en el diálogo de Preferencias.

Add in Preferences , if I do this, intent to add from Python Preferences a forbidden red signal not let me and when I write the enumere of Lilypond app nothing occurs ant don’t runs.

**Comment by Davidrobla** [comment] 2020-05-28 06:15
> El 26 may 2020, a las 6:15, David Rodríguez Blanco <ozadrb46@gmail.com> escribió:
> 
> Thank you for your mail and for your time. I apologize for my English and my inhability.
> I try to answer your questions in bold:
> Frescobaldi was installed with GitHub but I also downland MacPorts, not sure if installation was completed with with GItHub or MacPorts.
> In my Desktop I can see the Frescobaldi Icon and Lilypod icons, also booth are in Finder Applications.
> Ihave remover all the lowlands fo Lilypod I ge Lilypon 6.24.47 app.
> Frescobaldi inhalation says Congratulations   has been installed successfully and complete and compiled and a pop pdf sheet with music notes appears Conngratulations compitation completed successfully.
> When I try to open Frescobaldi from Terminal or from the icon in Desktop the program runs without problems and open.In Terminal the Frescobaldi icon don’t appears in the Dock,when lunch inTerminal a por Python launcher icon pops in The Dock, when lunch for the Destop icono the Frescobaldi icon appears in the Dock.
> Trying to set Preferences both with Terminal and from the Desktop the  program not l et me to accomplish it and always the same message:”Cannot init Lilypod, test the path and permissions adda in Preferences.
> Sorry but the same problem continues.
> I apologize, but I think I Cannot make it to run.
> Thank y ou.
> 
PD
/LilyPond\ 6.29.47.app lilypond
-bash: /Users/davidrodriguezblanco/Desktop/LilyPond 6.29.47.app: is a directory
MacBook-Air-de-David:~ davidrodriguezblanco$

**Comment by dliessi** [comment] 2020-06-09 23:49
@Davidrobla Sorry for the delay in answering.

To add your LilyPond installation in Frescobaldi's preferences, have you tried clicking on the button with the directory icon, instead of manually writing the path in the text box?

This is what I do.
1. Open Frescobaldi's preferences (the "Preferences" menu entry is either in the "Frescobaldi" menu or in the "Edit" menu).
2. Select the "LilyPond preferences" tab.
3. Click on "Add".
4. Click on the button with the directory icon.
5. Navigate to the desired LilyPond application, select it and click the "Open" button.
6. Optionally change the text in the "Label" text box.
7. Click the "OK" button.
8. Click the "OK" button to save and close the preferences.

Can you try these steps and tell me *precisely* where they fail?
If they all succeed, try engraving a simple file, e.g.
```
{ c' }
```

If there are already entries in the "LilyPond preferences" tab, you may remove them before step 3, or use "Engrave (custom)" from the "LilyPond" menu to engrave the test file, so that you can select the LilyPond application you have just added.

-----

A couple of additional notes.
* There is no need to keep dragging&dropping the application in the Terminal. That was a test I needed only once.
* There exists no version 6.29.47 of LilyPond. This is not a problem, the application can be named any way you want, but it might be confusing to have a nonexistent version number in the name. You could find out the real version number (right-click on the application, "Get Info") and rename it accordingly. Alternatively, if you plan to always have only one version of LilyPond at a time, you could simply rename it as "LilyPond" as it originally was: this way when you update LilyPond you can just replace the application and Frescobaldi will pick the new version automatically.
* I would recommend that you put applications in the "/Applications" directory, instead of the desktop or the "Downloads" directory.

**Comment by Davidrobla** [comment] 2020-06-11 16:23
Thank you for your time. I get it , now is running. The output is the note c’. I sent to the trash all my lowlands and make a new search for the the newest version fo Lilypod for Mac. Then I type your instructions and I could without problems add it in Preferences and it runs.Thank you very much.

**Closed** 2020-06-12 07:44 UTC
Labels: macosx
