### ISSUE TITLE
RuntimeError: wrapped C/C   object of type TabBar has been deleted

### ISSUE THREAD

**Issue by antoc1785** [frescobaldi/frescobaldi#1767] opened 2024-06-27 16:47 UTC
Traceback (most recent call last):
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.10/frescobaldi_app/mainwindow.py", line 335, in closeEvent
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.10/frescobaldi_app/mainwindow.py", line 353, in queryClose
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.10/frescobaldi_app/document.py", line 263, in close
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.10/frescobaldi_app/signals.py", line 191, in emit
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.10/frescobaldi_app/signals.py", line 308, in call
RuntimeError: wrapped C/C   object of type TabBar has been deleted

Opcionalmente, describa debajo lo que estaba haciendo:

I was using the Arm64 version but suddenly stopped working. It didn't open (app not responding).
So I tried uninstalling and install the x86_64 and got this error.

I appreciate any help

Frescobaldi: 3.3.0
Extension API: 0.9.0
Python: 3.10.10
python-ly: 0.9.7
Qt: 5.15.3
PyQt: 5.15.7
sip: 6.6.2
qpageview: 0.6.2
poppler: 22.9.0
python-poppler-qt: 21.3.0
OS: macOS-14.5-x86_64-i386-64bit
installation kind: standalone .app bundle

**Comment by fedelibre** [comment] 2024-06-30 20:36
duplicate of #1467

**Closed by fedelibre** 2024-06-30 20:36 UTC
