### ISSUE TITLE
Default language of Frescobaldi home page is Dutch

### ISSUE THREAD

**Issue by torqueville** [frescobaldi/frescobaldi#1162] opened 2019-08-22 10:06 UTC
Hi!

I notice that the "Nederlandse versie" is the default version of the frescobaldi.org home page. 

Could that be off-putting to many users? 

Sure if you are interested enough you'll find the small letter "English version" link at the bottom of the Frescobaldi home page, but... 

Best, 
  Concerned Frescobaldi user

**Comment by wbsoft** [comment] 2019-09-21 20:54
Strange, `index.html` is in english, `index.nl.html` is Dutch...

**Comment by fedelibre** [comment] 2019-09-27 13:38
The files are correct. In fact http://frescobaldi.org/index.html is in english.
The problem is that http://frescobaldi.org/ serves index.nl.html instead of index.html

Some server setting should be fixed.

**Comment by wbsoft** [comment] 2019-09-27 18:07
I have been looking at it. But couldn't yet find why nl is served by default. Will investigate further...

**Comment by Nodd** [comment] 2020-01-04 15:01
Worse: Clicking the "Download" link on the English page http://frescobaldi.org/index.html sends to http://frescobaldi.org/download which is in Dutch. The corresponding page in English is http://frescobaldi.org/download.html.

**Comment by wbsoft** [comment] 2020-01-04 21:09
It seems the server ignores the language preference from the HTTP request. Will try to find out why...

**Comment by wbsoft** [comment] 2020-01-04 21:37
I think it works now!

**Comment by uliska** [comment] 2020-01-05 06:13
Seems to work for me.

**Closed** 2020-01-05 13:32 UTC

**Comment by Nodd** [comment] 2020-01-05 18:40
Works for me too, thanks !
