### ISSUE TITLE
AttributeError: 'WebEngineDummy' object has no attribute 'view'

### ISSUE THREAD

**Issue by humanlanguage** [frescobaldi/frescobaldi#1745] opened 2024-03-15 18:54 UTC
Traceback (most recent call last):
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.10/frescobaldi_app/panel.py", line 64, in sizeHint
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.10/frescobaldi_app/panel.py", line 71, in widget
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.10/frescobaldi_app/objecteditor/__init__.py", line 47, in createWidget
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.10/frescobaldi_app/objecteditor/widget.py", line 55, in __init__
AttributeError: 'WebEngineDummy' object has no attribute 'view'

Opcionalmente, describa debajo lo que estaba haciendo:

Frescobaldi: 3.3.0
Extension API: 0.9.0
Python: 3.10.10
python-ly: 0.9.7
Qt: 5.15.8
PyQt: 5.15.9
sip: 6.7.6
qpageview: 0.6.2
poppler: 23.3.0
python-poppler-qt: 21.3.0
OS: macOS-14.4-arm64-arm-64bit
installation kind: standalone .app bundle

**Comment by fedelibre** [comment] 2024-03-18 22:21
Seems a duplicate of #1677

**Closed by fedelibre** 2024-03-18 22:21 UTC
