### ISSUE TITLE
Frescobaldi 3.1.3 (Linux) throws an error when attempting to use the documentation search

### ISSUE THREAD

**Issue by amca01** [frescobaldi/frescobaldi#1416] opened 2022-01-15 11:38 UTC
At the top of the documentation browser is a pull-down menu, which on my system has just the one entry: 2.22.1 (lilypond.org).  Next to that is a search box (with the word "search" in light grey).  But if I enter a character in that search box, I get a popup error:

    Traceback (most recent call last):
      File "/usr/lib/python3.10/site-packages/frescobaldi_app/widgets/lineedit.py", line 63, in _updateClearButton
        b.move(x, y)
    TypeError: arguments did not match any overloaded call:
      move(self, QPoint): argument 1 has unexpected type 'int'
      move(self, int, int): argument 2 has unexpected type 'float'

This means that if I want to search the documentation from within Frescobaldi, I have to go back to the "Documentation index" (which is the home page), and use the search box there - which does work.  

It would be very convenient to use the search bar at the top of the browser, if possible!

**Comment by fedelibre** [comment] 2022-01-17 23:29
It works correctly on Frescobaldi flatpak package (version 3.1.3, python version 3.8.12).

I just tried running Frescobaldi from master using python 3.10 and I can reproduce your error.
The webpage is not loaded at all actually, see:

![Screenshot from 2022-01-18 00-25-42](https://user-images.githubusercontent.com/1644647/149847297-96a60959-821c-4c42-a623-b18d590a92d1.png)

@wbsoft @dliessi Maybe you can fix it before the next release?

**Comment by amca01** [comment] 2022-01-17 23:38
Thank you - the documentation browser does work in my version:

Frescobaldi: 3.1.3
Extension API: 0.9.0
Python: 3.10.1
python-ly: 0.9.7
Qt: 5.15.2
PyQt: 5.15.6
sip: 6.1.0.dev2104271705
poppler: 21.11.0
python-poppler-qt: 21.1.0
OS: Linux-5.16.0-arch1-1-x86_64-with-glibc2.33

but as I say the only thing which doesn't is the search bar (which is shown in your image).

**Comment by fedelibre** [comment] 2022-01-28 14:34
I can reproduce your error on Frescobaldi current master (python 3.10):

```
Traceback (most recent call last):
  File "/var/home/fede/src/frescobaldi/frescobaldi/frescobaldi_app/widgets/lineedit.py", line 63, in _updateClearButton
    b.move(x, y)
TypeError: arguments did not match any overloaded call:
  move(self, QPoint): argument 1 has unexpected type 'int'
  move(self, int, int): argument 2 has unexpected type 'float'
```

**Comment by tinpan-io** [comment] 2022-03-31 21:35
I just encountered this in the `community/frescobaldi` 3.1.3-5 package in Manjaro Linux 21.2.5 (Python 3.10.2)

In my case I was trying to use the search bar in the "Keyboard Shortcuts" preferences pane.

**Comment by MJE10** [comment] 2022-05-19 18:30
This seems to be related to #1398, #1433 and #1417

**Comment by fedelibre** [comment] 2023-01-24 22:27
I can't reproduce it anymore on python 3.10.7 and Frescobaldi current master. `widgets/lineedit.py` was removed with commit 97ab0991bd8a70971733c67afe5d62a05ba5b879

Let's close it.

**Closed by fedelibre** 2023-01-24 22:27 UTC
