### ISSUE TITLE
Music view crashes with python errors on Ubuntu 17.04

### ISSUE THREAD

**Issue by ssmus** [frescobaldi/frescobaldi#929] opened 2017-04-13 23:20 UTC
Compiling the following file:
\version "2.19.59"
{ c' d' e' f' }

Under the following system:
Frescobaldi: 3.0.0
Python: 3.5.3
python-ly: 0.9.4
Qt: 5.7.1
PyQt: 5.7
sip: 4.18.1
poppler: 0.44.0
python-poppler-qt: 0.24.2
OS: Linux-4.10.0-19-generic-x86_64-with-Ubuntu-17.04-zesty

Results in this error:
Traceback (most recent call last):
  File "/usr/share/frescobaldi/frescobaldi_app/musicview/pointandclick.py", line 44, in links
    return _cache[document]
  File "/usr/lib/python3.5/weakref.py", line 394, in __getitem__
    return self.data[ref(key)]
KeyError: <weakref at 0x7f2d72c8d958; to 'Document' at 0x7f2d72cf8708>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/frescobaldi/frescobaldi_app/musicview/widget.py", line 116, in openDocument
    self._links = pointandclick.links(document)
  File "/usr/share/frescobaldi/frescobaldi_app/musicview/pointandclick.py", line 54, in links
    t = textedit.link(link.url())
  File "/usr/share/frescobaldi/frescobaldi_app/textedit.py", line 48, in link
    m = textedit_match(url)
TypeError: expected string or bytes-like object

Also, opening a file that already has an engraved pdf triggers the error.

**Comment by syntaxaire** [comment] 2017-04-23 17:39
This looks like a bug either in python-poppler-qt5 or its Ubuntu package - calling url() on a popplerqt5.LinkBrowse is supposed to return a url, but instead it is returning a PyQt5.QtCore.QStorageInfo.

From debug session of Frescobaldi:
```
In[6]: link
Out[7]: 
<popplerqt5.LinkBrowse at 0x7fe06ef0dee8>
In[7]: link.url()
Out[8]: 
<PyQt5.QtCore.QStorageInfo at 0x7fe06ed76eb8>
```

**Comment by derbuur** [comment] 2017-05-09 18:19
I can confirm the error

**Comment by dliessi** [comment] 2017-07-31 10:52
> I can confirm the error

Me too.

**Comment by CJBrew** [comment] 2018-03-15 09:46
Is there a fix? 

Every time I try to use Linux to get things done I come up against dependency issues. Going back to Windows, again. Stuff works.....

**Comment by uliska** [comment] 2018-03-15 10:09
How was Frescobaldi installed, OS package or manually?

*If* a distribution has Frescobaldi 3 as a package it should work. If manual installation is required there is (by now) a comprehensive installation guide: https://github.com/wbsoft/frescobaldi/wiki/Run-Frescobaldi-3-on-Linux, also including a compatibility matrix for several distributions.

The thing seems to be to install the external dependencies through the package manager and the two Frescobaldi related ones (frescobaldi and python-ly) from their Github repositories. Most problems that had been reported in the discussion leading to the Wiki page stemmed from packages installed through Pip or from outdated distribution repositories.

**Comment by CJBrew** [comment] 2018-03-15 13:33
I seem to have fixed it by

- Uninstalling older dependencies and versions of frescobaldi etc via api
- Installing the new build of poppler as per another post here
- Reinstalling Frescobaldi (using the `sudo python setup.. ` command)

**Comment by kunom** [comment] 2018-03-15 18:02
I am on the latest Ubunutu, and I don't get that `weakref.getitem` error any more since quite some time. Before, I had it with 100% reproduction rate when enabling "Music View".

**Comment by wbsoft** [comment] 2019-11-22 05:48
Closing, not a frescobaldi/popplerqt5 bug.

**Closed by wbsoft** 2019-11-22 05:48 UTC
