### ISSUE TITLE
engrave to svg hangs when engraving mutliplte times

### ISSUE THREAD

**Issue by bartart3d** [frescobaldi/frescobaldi#92] opened 2012-11-21 09:12 UTC
I have had this problem a number of times, it should be reproducable. When I have a lilypond file and engrave it to get a preview, it never is a problem, but when I want to engrave it as a svg file, it often happens that frescobaldi hangs after the second engraving to svg.

It most often happens when I first render to a pdf, then I think it's ok, and render it to svg, but then I notice something still off, and I modify it. Next I render to preview again, and when I want to render it to an svg, frescobaldi hangs after pressing the required button.

**Comment by fedelibre** [comment] 2023-12-26 20:48
I'll close this issue since there's not enough information to investigate if there's a problem in Frescobaldi.
Perhaps it was a lilypond problem  to cause the freeze of Frescobaldi.

@bartart3d Feel free to reopen the issue if you are still able to reproduce it. Please share the source file (or send it to me by email if you cannot share it publicly) so we can try to reproduce it.

**Closed by fedelibre** 2023-12-26 20:48 UTC
