### ISSUE TITLE
Bug: SVG/PDF/EPS export add white background to part of page

### ISSUE THREAD

**Issue by lfm83** [frescobaldi/frescobaldi#1317] opened 2020-06-19 18:52 UTC
In some constellations involving content spread out over a page, the SVG/PDF/EPS export filter adds a white background covering part of the selected area.

![grafik](https://user-images.githubusercontent.com/14637077/85171094-a30e6e00-b26e-11ea-9167-9dcd2defbab6.png)

(I never filed a bug report on GitHub before, so please inform me if I made fundamental mistakes.)

**Comment by uliska** [comment] 2020-06-19 18:55
No, everything's fine (except the existence of a bug) ;-)

Can you specify "in some constellations" a bit more?
And: is this solid background definitely created in Frescobaldi's export and not present in LIlyPond's SVG output?

**Comment by lfm83** [comment] 2020-06-19 19:01
Specifying "in some constellations": Not easily. It comes up all the time in my work (since I frequently copy&paste music examples into LibreOffice Impress presentations, where I notice the solid part-background all the time). In the example document I posted, the error comes up as soon as I select _both_ the music and the tagline, not if I only catch one of them.

This should already rule out the existence of the background in LilyPond's SVG output, as far as I can see. (And are you sure that the SVG export actually _uses_ LilyPond's SVG backend?) But anyway, I can't see such a background if I compile to SVG and open the resulting file in Inkscape.

**Comment by lfm83** [comment] 2020-06-22 08:12
Ok, some more information: This has nothing to do with LilyPond whatsoever, as can be seen by tricking Frescobaldi into using a non-LilyPond PDF file (just replace a PDF file generated by LilyPond by something else when Frescobaldi is not working).

The white box always comes from the upper left part of each page, but its size seems to vary: Its neither a fixed part of the selection nor a fixed white box on the paper.

![grafik](https://user-images.githubusercontent.com/14637077/85264196-9eb1a300-b470-11ea-8179-289e80a81cde.png)
![grafik](https://user-images.githubusercontent.com/14637077/85264312-cd2f7e00-b470-11ea-9fe0-4d5216afbcd5.png)

**Comment by wbsoft** [comment] 2020-06-28 18:03
Try the newest poppler library with Arthur

**Comment by fedelibre** [comment] 2023-12-27 09:19
I'm closing this issue since cannot reproduce it on Frescobaldi 3.3.0, either with Arthur enabled or not.

If anyone wants to try, you have to select the music in the Music Preview using the mouse right-click and dragging the selection, then select Copy to image. In the next window set a background color to see how it's applied.

![immagine](https://github.com/frescobaldi/frescobaldi/assets/1644647/5b7ef3c1-a2ea-489b-baf2-b40622e0f639)

**Closed by fedelibre** 2023-12-27 09:19 UTC
Labels: defect
