### ISSUE TITLE
[Wayland?] Creating extra window and closing it segfaults

### ISSUE THREAD

**Issue by jeanas** [frescobaldi/frescobaldi#1710] opened 2023-11-10 10:30 UTC
On my system with the freshly released Fedora 39, if I create a second window (by  selecting “Window > New Window”), then I close this window, it reliably segfaults (but nothing happens if I close the original window).

It's apparently crashing somewhere deep in QtWayland:

```
#0  0x00007fd4cd734958 in QtWaylandClient::QWaylandAbstractDecoration::update() () at /lib64/libQt5WaylandClient.so.5
#1  0x00007fd4cd72565b in QtWaylandClient::QWaylandDisplay::handleKeyboardFocusChanged(QtWaylandClient::QWaylandInputDevice*) () at /lib64/libQt5WaylandClient.so.5
#2  0x00007fd4cd725705 in QtWaylandClient::QWaylandInputDevice::Keyboard::handleFocusLost() () at /lib64/libQt5WaylandClient.so.5
#3  0x00007fd4d32e8821 in void doActivate<false>(QObject*, int, void**) () at /lib64/libQt5Core.so.5
#4  0x00007fd4cd726302 in QtWaylandClient::QWaylandWindow::reset() () at /lib64/libQt5WaylandClient.so.5
#5  0x00007fd4cd72647b in QtWaylandClient::QWaylandWindow::~QWaylandWindow() () at /lib64/libQt5WaylandClient.so.5
#6  0x00007fd4d3ab5f29 in non-virtual thunk to QtWaylandClient::QWaylandEglWindow::~QWaylandEglWindow() ()
    at /usr/lib64/qt5/plugins/wayland-graphics-integration-client/libqt-plugin-wayland-egl.so
#7  0x00007fd4cf977861 in QWindowPrivate::destroy() () at /lib64/libQt5Gui.so.5
#8  0x00007fd4ce9d875d in QWidgetPrivate::deleteTLSysExtra() () at /lib64/libQt5Widgets.so.5
#9  0x00007fd4ce9e76a8 in QWidget::destroy(bool, bool) () at /lib64/libQt5Widgets.so.5
#10 0x00007fd4ce9eed54 in QWidget::~QWidget() () at /lib64/libQt5Widgets.so.5
#11 0x00007fd4cf263525 in release_QMainWindow.lto_priv.0 () at /usr/lib64/python3.12/site-packages/PyQt5/QtWidgets.abi3.so
#12 0x00007fd4d35a1b91 in forgetObject () at /usr/lib64/python3.12/site-packages/PyQt5/sip.cpython-312-x86_64-linux-gnu.so
#13 0x00007fd4d35a1c98 in sipWrapper_dealloc.lto_priv.0 () at /usr/lib64/python3.12/site-packages/PyQt5/sip.cpython-312-x86_64-linux-gnu.so
#14 0x00007fd4e1836455 in subtype_dealloc () at /lib64/libpython3.12.so.1.0
#15 0x00007fd4e181d4c0 in method_dealloc () at /lib64/libpython3.12.so.1.0
#16 0x00007fd4d3592e20 in sip_api_call_procedure_method () at /usr/lib64/python3.12/site-packages/PyQt5/sip.cpython-312-x86_64-linux-gnu.so
#17 0x00007fd4cf265a6b in sipQMainWindow::closeEvent(QCloseEvent*) () at /usr/lib64/python3.12/site-packages/PyQt5/QtWidgets.abi3.so
#18 0x00007fd4ce9f3698 in QWidget::event(QEvent*) () at /lib64/libQt5Widgets.so.5
```

Not sure if this is a Qt or Wayland bug, or if we're doing something wrong.

**Comment by fedelibre** [comment] 2023-12-26 16:12
I cannot reproduce it on Fedora 39 (Silverblue) using Frescobaldi flatpak. Perhaps it's some dependency version different from the one used by flatpak? Which version of Qt are you using?

These are the  current versions in flatpak:

```
Frescobaldi: 3.3.0
Extension API: 0.9.0
Python: 3.11.5
python-ly: 0.9.8
Qt: 5.15.10
PyQt: 5.15.10
sip: 6.7.12
qpageview: 0.6.2
poppler: 21.8.0
python-poppler-qt: 21.3.0
OS: Linux-6.6.7-200.fc39.x86_64-x86_64-with-glibc2.38
```

**Comment by fedelibre** [comment] 2023-12-26 20:36
I cannot reproduce it either using the rpm package or running from git  master.
Versions:

```
Frescobaldi: 3.3.0
Extension API: 0.9.0
Python: 3.12.0
Git branch: master
on commit: 93991784
python-ly: 0.9.7
Qt: 5.15.11
PyQt: 5.15.9
qpageview: 0.6.2
poppler: 23.2.0
python-poppler-qt: 21.3.0
OS: Linux-6.6.7-200.fc39.x86_64-x86_64-with-glibc2.38 (Fedora Linux 39 (Container Image))
Installation kind: distro package or installed from source
```

**Comment by fedelibre** [comment] 2024-11-27 12:47
@jeanas Can you still get this segfault on Fedora 41?

I'll close this as I cannot reproduce it.

**Closed by fedelibre** 2024-11-27 12:47 UTC
Labels: wayland

**Comment by jeanas** [comment] 2024-11-27 16:15
It's working fine for me now.
