### ISSUE TITLE
Problem to open Frescobaldi

### ISSUE THREAD

**Issue by filipedfs** [frescobaldi/frescobaldi#1310] opened 2020-05-25 03:19 UTC
![image](https://user-images.githubusercontent.com/13025635/82775131-2e861200-9e1d-11ea-8e6a-5c559d371721.png)

This window appears after I installed Frsecobaldi 3.1.2. "Jones.000" is not me...

**Comment by fedelibre** [comment] 2020-05-25 07:42
Duplicate of #1252 

Workaround: uninstall and install again from scratch

**Closed by fedelibre** 2020-05-25 07:42 UTC
