### ISSUE TITLE
AttributeError: 'NoneType' object has no  attribute 'toolcommand'

### ISSUE THREAD

**Issue by wbsoft** [frescobaldi/frescobaldi#1355] opened 2021-01-21 12:13 UTC
Reported by a user: Importing a MusicXML file fails on Mac OS X.

```
Frescobaldi: 3.1.3
Extension API: 0.9.0
Python: 3.9.1
python-ly: 0.9.7
Qt: 5.11.3
PyQt: 5.15.2
sip: 4.19.24
poppler: 20.12.1
python-poppler-qt: 0.75.0
OS: macOS-10.13.6-x86_64-i386-64bit
installation kind: standalone .app bundle

Traceback (most recent call last):
  File
"/Applications/Frescobaldi.app/Contents/Resources/lib/python3.9/frescobaldi_app/file_import/toly_dialog.py",
line 140, in about_to_accept
  File
"/Applications/Frescobaldi.app/Contents/Resources/lib/python3.9/frescobaldi_app/file_import/musicxml.py",
line 112, in configure_job
  File
"/Applications/Frescobaldi.app/Contents/Resources/lib/python3.9/frescobaldi_app/file_import/toly_dialog.py",
line 150, in configure_job
AttributeError: 'NoneType' object has no attribute 'toolcommand'

Optionally describe below what you were doing:

I was trying to import a musicxml file.
```

**Comment by dliessi** [comment] 2023-03-20 00:34
I cannot reproduce this.

**Comment by dliessi** [comment] 2023-03-24 22:18
I believe that this depends on #1492: reading the relevant code in `file_import/tolydialog.py`, `lilychooser.py`, `lilypondinfo.py` and `macosx/__init__.py` I think that `self._info` is `None` because on recent macOS there is no preinstalled Python, so `system_python` returns `None`.

I'm closing this issue now, as we are about to merge #1565, which solves #1492.

**Closed by dliessi** 2023-03-24 22:18 UTC
Labels: macOS
