### ISSUE TITLE
reconsider translation tools and process

### ISSUE THREAD

**Issue by fedelibre** [frescobaldi/frescobaldi#1099] opened 2018-08-29 09:11 UTC
[Original mailing list "discussion"](https://groups.google.com/forum/#!msg/frescobaldi/ROVJg4mRS3M/D8t_wxjdCAAJ), triggered by the problem described in issue #1040.
Here's a more detailed and hopefully precise description.

## Custom scripts or external tools?

Frescobaldi uses custom scripts to manage all the translations. I wonder if today there are better and widespread tools we can use instead.
There are two pot files to be generated: application and user manual.  (Current script merge these files together in a single pot file, which may be convenient for translators and may encourage them to translate everything. However, other software projects keep application and user guide translations separate. This is something that may be rediscussed if we consider a change in the tools.)

1. **User manual pot** is generated by [md2pot.py](../frescobaldi_app/po/md2pot.py). This is the script which should be fixed to solve issue #1040. As alternative I found [this extension](https://pypi.org/project/markdown-i18n/) of [Python Markdown](https://python-markdown.github.io/).

2. **Application pot** is generated by a xgettext command defined in [update-pot.py](../frescobaldi_app/po/update-pot.py).

3. Finally, the po and mo files generated in the [Makefile](../frescobaldi_app/po/Makefile) by regular gettext commands (msgmerge and msgfmt) are checked by another custom script, [molint.py](../frescobaldi_app/po/molint.py); this uses a custom module named [mofile.py](../frescobaldi_app/po/mofile.py), which was written in 2011 and was heavily inspired by the Python gettext library but with some additional features. Don't know if it's still true after 7 years.. I mean, [gettext library](https://docs.python.org/3.7/library/gettext.html) might be improved.

## Exclude mo files from Git index

.mo files are generated from the .po files but also tracked in Git. Is this a good practice?

@dliessi [recently commented](https://github.com/wbsoft/frescobaldi/pull/1098#issuecomment-416534911):

> I would be in favor of removing the mo files from the repository, given that they are generated programmatically, provided that we either make sure that we generate and include them in source releases, or include gettext in the build requirements and adapt setup.py to automatically generate mo files before installing.
> Until that time, I think that we should keep including and updating the mo files in the repository.

@wbsoft please let us know your thoughts

**Comment by wbsoft** [comment] 2019-11-06 14:39
Indeed the mo files need not be in the repository as they are generated. Originally I put them there so users need no build phase before Frescobaldi can be used. The mo files are also checked for wrong variable names.

But we can move the mo creation stage to setup.py. Because I always check proper installing before releasing this is not a real problem. Only gnu gettext needs to be available in order to install Frescobaldi then.

**Comment by fedelibre** [comment] 2019-11-06 16:35
> There are two pot files to be generated: application and user manual. (Current script merge these files together in a single pot file, which may be convenient for translators and may encourage them to translate everything. However, other software projects keep application and user guide translations separate. This is something that may be rediscussed if we consider a change in the tools.)

I've been thinking again about this lately.
My feeling is that keeping application and user manual translation separated is a better idea, mainly because it allows someone to commit to as much work as he/she wants: e.g. translating only the application but not the user manual. This is especially true if the user manual is going to be expanded, as I think Urs wrote somewhere (@uliska correct me if I'm wrong).

A single PO file may be an incentive to translate all... or nothing.
For example, I stopped updating Denemo translation because the application PO strings grew too much with a lot of information, like a user manual.

**Comment by fedelibre** [comment] 2019-11-06 16:37
> But we can move the mo creation stage to setup.py. Because I always check proper installing before releasing this is not a real problem. Only gnu gettext needs to be available in order to install Frescobaldi then.

I'm in favour of this.

**Comment by wbsoft** [comment] 2019-11-06 16:47
Ok, I'll split the pot file and move the po and pot files outside the frescobaldi_app tree, and only install the mo files, which will be created in the build stage.

**Comment by uliska** [comment] 2019-11-06 17:08
> e.g. translating only the application
>but not the user manual. This is especially true if the user manual is
>going to be expanded, as I think Urs wrote somewhere (@uliska correct
>me if I'm wrong).
>

Well, *going* to be expanded is optimistic. My take is that it *has to be* extended substantially.
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by wbsoft** [comment] 2019-11-06 17:42
> A single PO file may be an incentive to translate all... or nothing.
> For example, I stopped updating Denemo translation because the application PO strings grew too much with a lot of information, like a user manual.

Good point. I think we face the same issue. It is fine when the application's message file remains relatively small.

There is one issue: currently the application and userguide pot files are merged into one `frescobaldi.pot`, removing duplicate messages. I'll try to make sure that the separate userguide pot file does not duplicate strings that are in the application's pot file, so that double work is eliminated :-)

**Comment by fedelibre** [comment] 2019-11-06 20:37
I think that Translation Memory feature of PO editors would mitigate this duplication problem, in case avoiding duplication in another file was too complex.

**Comment by wbsoft** [comment] 2019-11-07 13:32
Today I evaluated the gettext module from the python standard library, but it still does not support the msgctxt feature of MO files, which is used by Frescobaldi to provide translations based on context (see README-translations). So we continue to use the mofile module which is simple and robust. 

I'll split the po files for app and userguide, so the larger text strings in the userguide do not put off application translators.

The mo files will be removed from version control, but they remain in source dist. So it is still possible to run Frescobaldi from the source tree, and a build phase won't be required.

**Comment by wbsoft** [comment] 2019-11-08 13:36
Master now has the po files separate for frescobaldi and userguide in the toplevel i18n/ directory. The MO files are not under version control anymore, but they are generated and put in frescobaldi_app/i18n/ (the old name po made no sense anymore).

Generating the MO files is as simple as `make -C i18n`; will try to add that step to the `sdist` setup.py command, so the distributed tar balls have the mo files.

**Comment by wbsoft** [comment] 2019-11-08 15:24
Closing this, reopen if you think not all problems are solved :-)

**Closed by wbsoft** 2019-11-08 15:24 UTC

**Comment by fedelibre** [comment] 2019-11-14 08:02
@wbsoft I think problems are solved. I'm updating the translation and I'll see if I find any problem.

Just a remark.. don't know if it used to work before.. I cannot jump to source from my PO editor because the source file locations go back only one directory instead of two. So for example:

```
#: ../frescobaldi_app/about.py:56
msgid "About"
msgstr "Informazioni"
```

should be:

```
#: ../../frescobaldi_app/about.py:56
msgid "About"
msgstr "Informazioni"
```

I don't think that gettext has an option to set a different path though.
It depends on the current working directory when the xgettext command is run?

**Comment by wbsoft** [comment] 2019-11-14 20:23
Good point! It's caused by the fact that the po file is one directory up in the path. I could move all ll_CC/frescobaldi.po to frescobaldi-ll_CC.po etc...

**Comment by wbsoft** [comment] 2019-11-15 05:59
I put sed commands in the Makefile to rewrite the paths :-)

**Comment by fedelibre** [comment] 2019-11-30 22:59
@wbsoft I have some questions.

Because of the sed commands above I had to rebase the translation I was doing before your commit. As I'm not sure I've resolved the conflicts correctly, I'd be safer if I could update the italian po files. This is not documented in README-translations... I tried the following:

```
cd i18n
make pot
make frescobaldi
```

(BTW, it would be nice if I could update only my language po files instead of all languages)

but then I see that a new ../ is added to the ../.. already present:

```
[fede@localhost i18n]$ git diff it/frescobaldi.po
diff --git a/i18n/it/frescobaldi.po b/i18n/it/frescobaldi.po
index a3bc3e59..91026007 100644
--- a/i18n/it/frescobaldi.po
+++ b/i18n/it/frescobaldi.po
@@ -21,164 +21,164 @@ msgstr ""
 "Plural-Forms: nplurals=2; plural=(n != 1)\n"
 "X-Generator: Gtranslator 3.34.0\n"
 
-#: ../../frescobaldi_app/about.py:49
+#: ../../../frescobaldi_app/about.py:49
 #, python-brace-format
 msgid "About {appname}"
 msgstr "A proposito di {appname}"
 
-#: ../../frescobaldi_app/about.py:56
+#: ../../../frescobaldi_app/about.py:56
 msgid "About"
 msgstr "Informazioni"

[...]
```

What I'm missing?

```
$ msgmerge --version
msgmerge (GNU gettext-tools) 0.20.1
```

**Comment by wbsoft** [comment] 2019-12-01 10:55
Normally the sed command is only run when the po needed to be updated, so double addition of `../` should not happen. But I will look into it. You can update one po file using `make nl/nl.po` eg.

**Comment by fedelibre** [comment] 2019-12-19 12:02
I'm reopening this issue, as I'm not totally satisfied by the current workflow and/or documentation.

I have a translation patch ready since a few weeks, but I wanted to read through the manual before submitting it. In the meanwhile, some changes were made to the translation tool *and* to the po files, which forced me to rebase my pending work. Rebasing a po file is not fun at all and error-prone. Maybe there's a better way to solve conflicts, but should be documented.
I guess there is some gettext tool to intelligently merge two po files. For example, GNOME Damned Lies web service, if you submit a PO file while the POT has changed, generates a new PO file which you can start working on right away.

**Comment by wbsoft** [comment] 2019-12-19 12:56
You can just overwrite the (re-generated) po file (that has conflicts) with your last edited version. Then, if updating the po files again, the po files is regenerated, but your changes are retained. Then commit the updated version.

**Comment by fedelibre** [comment] 2019-12-19 21:56
Well, it works :-)
